theme: Architect
title: Opis projektu
description: Celem projektu jest stworzenie aplikacji na telefon, która pozwoli użytkownikom umawiać się na spotkania. W celu realizacji projektu wykorzystamy bibliotekę Kivy.
